environment:
  matrix:
  - TOXENV: "py27"
  - TOXENV: "py35"
  - TOXENV: "py36"
  - TOXENV: "linting"
  - TOXENV: "docs"

install:
  - echo Installed Pythons
  - dir c:\Python*

  - C:\Python36\python -m pip install tox

build: false

test_script:
  - C:\Python36\Scripts\tox
