name: main

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        tox_env: ["py36", "py37", "py38", "py39", "py310"]
        os: [ubuntu-latest, windows-latest]
        include:
          - tox_env: "py36"
            python: "3.6"
          - tox_env: "py37"
            python: "3.7"
          - tox_env: "py38"
            python: "3.8"
          - tox_env: "py39"
            python: "3.9"
          - tox_env: "py310"
            python: "3.10"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
