name: test

on:
  push:
    branches:
      - main
      - "test-me-*"
  pull_request:

# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        tox_env: ["py310", "py311"]
        os: [ubuntu-latest, windows-latest]
        include:
          - tox_env: "py310"
            python: "3.10"
          - tox_env: "py311"
            python: "3.11"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}
